AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  PublicSubnetA:
    Type: String
    Default: #Add Subnet ID
  PrivateSubnetB:
    Type: String
    Default: #Add Subnet ID
  AMI:
    Type: String
    Default: #Add AMI ID
  KeyPair:
    Type: String
    Default: #Add EC2 KeyPair Name

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      AccessConfig:
        AuthenticationMode: CONFIG_MAP
      Name: EKSCluster
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !ImportValue EKSSecurityGroupId
        SubnetIds:
          - !Ref PublicSubnetA
          - !Ref PrivateSubnetB
      RoleArn: !ImportValue EKSRoleArn
      Version: "1.29"

  EKSLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EKSLaunchTemplate
      LaunchTemplateData:
        InstanceType: t2.medium
        SecurityGroupIds:
          - !ImportValue EKSSecurityGroupId
        KeyName: !Ref KeyPair
        UserData: !Base64 |
          #!/bin/bash
          
          # Update the package repository and install required dependencies
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

          # Install Docker
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo useradd ec2-user
          sudo usermod -aG docker ec2-user

          # Install Kubernetes components (kubeadm, kubectl, kind)
          sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo snap install kubeadm --classic
          apt-mark hold kubeadm kubectl
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo cp ./kind /usr/local/bin/kind
          rm -rf kind

          # Install Helm
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

          # Install FluxCD
          curl -s https://fluxcd.io/install.sh | sudo bash

          # Install K9s
          wget https://github.com/derailed/k9s/releases/download/v0.24.7/k9s_Linux_x86_64.tar.gz
          tar -xzvf k9s_Linux_x86_64.tar.gz
          sudo mv k9s /usr/local/bin

          # Add kubectl bash completion
          echo "source <(kubectl completion bash)" >> ~/.bashrc